### PR TITLE
Connector: refresh token if needed before metadata exchange.

### PR DESCRIPTION
**Pull request by xjuan**
Fix issue #346 "Invalid token in metadata exchange"

### CODE REVIEW

**Comment by enocom** [comment]
Thanks for the PR @xjuan. Before we can look at this, we need you to sign the CLA.

See here for details: https://github.com/GoogleCloudPlatform/alloydb-python-connector/pull/347/checks?check_run_id=27567309191

**Comment by xjuan** [comment]
Hi the CLA was submitted my the CTO, not sure if it should refresh automatically or not

**Comment by enocom** [comment]
If look at https://github.com/GoogleCloudPlatform/alloydb-python-connector/pull/347/checks?check_run_id=27633672198, it will let you re-run the scan. I think right now the commit has a personal and a company email which is causing it to still fail.

**Comment by enocom** [comment]
We'd like to get this bug fixed and in a release ASAP. Thanks again for the issue @xjuan!

**Comment by enocom** [comment]
Replaced by https://github.com/GoogleCloudPlatform/alloydb-python-connector/pull/351.

**Comment by xjuan** [comment]
hi, sorry I was in a conference, thanks for taking care of this.

**Comment by enocom** [comment]
No problem. Thanks for the issue. On further digging we found the root cause (this was just a symptom): https://github.com/GoogleCloudPlatform/alloydb-python-connector/issues/357.

**Comment by enocom** [comment]
That's also been fixed in the latest release.

**Pull request closed without merging**
