### PR TITLE
feat: drop support for Python 3.8

### PR DESCRIPTION
**Pull request by rhatgadkar-goog**
Python 3.8 EOL was October 7, 2024: https://endoflife.date/python

### CODE REVIEW

**Review by enocom — APPROVED** [review]
Let's add a note about EOL and link to the Python announcement in the commit message.

**Comment by enocom** [comment]
Also you'll need to update the required checks to swap 3.9 for 3.8.

**Comment by rhatgadkar-goog** [comment]
> Also you'll need to update the required checks to swap 3.9 for 3.8.

These are the ones I update in the branch protection settings?

**Comment by rhatgadkar-goog** [comment]
> > Also you'll need to update the required checks to swap 3.9 for 3.8.
> 
> These are the ones I update in the branch protection settings?

I updated the branch protection settings, and it looks like the required checks are for 3.9 now. So I guess that was it

**Pull request merged**
